version: '2'
services:
  flink-master:
    image: ging/flink-master:1.7.2-hadoop2.8
    hostname: flink-master
    container_name: flink-master
    environment:
      - IDM_URL=http://192.168.0.13:3000
      - CLIENT_ID=fcf2ac8a-6ce9-4693-9fee-33bd790e1bf2
      - CLIENT_SECRET=0165691e-db07-47b6-a36d-e9c3f4757fa0
      - CALLBACK_URL=http://192.168.0.13/login
      - FLINK_PORT=8081
      - OAUTH_CLIENT_PORT=80
      - FLUENT_HOST=192.168.0.13
      - FLUENT_PORT=24225
#      - "constraint:node==<yourmasternode>"
    ports:
      - "8082:8080"
      - "8083:8081"
      - "80:80" # This is for the oauth client
    volumes:
      - access-token:/etc/oauth

  flink-worker:
    image: ging/flink-worker:1.7.2-hadoop2.8
    environment:
      - FLINK_MASTER_PORT_6123_TCP_ADDR=flink-master
      - FLUENT_HOST=192.168.0.13
      - FLUENT_PORT=24225
#     - FLINK_NUM_TASK_SLOTS=2
#    - "constraint:node==<yourworkernode>"
    ports:
      - "9002:9002"
      - "9001:9001"
    depends_on:
      - flink-master
    volumes_from:
      - flink-master

volumes:
  access-token:
